### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [Tal1a/bsa-lessons#4]
Привіт, @Tal1a. Як воно йде, порядок? Як на рахунок додати **README.md** до проекту? Просто з коротким описом репозиторію і лінками на статті.

**Comment by Tal1a** [comment]
Привіт. Добавила!) Гарного вечора!!

**Comment by volodymyr-kushnir** [comment]
Дякую. А ще глянь, будь ласка, [**лайфхаки і підказки**](https://github.com/volodymyr-kushnir/agenda), можливо щось корисним буде.

**Comment by volodymyr-kushnir** [comment]
@Tal1a закрив #4. Взагалі їх можна закривати автоматично, якщо дописувати до повідомлення **комміту** **"closes #4"** — **GitHub** парсить по ключових словах _fixed, fixes, closes, closed, resolves, resolved_ і автоматично закриває проблему з таким-то номером.

Ось приклад такого комміту https://github.com/volodymyr-kushnir/recipes/commit/b08144f79a6629cc07173fc02cccc9b2f89317e7

**Comment by Tal1a** [comment]
Ok

**Comment by Tal1a** [comment]
!! fixes #4
